plugins { id 'com.android.application' }

android {
    namespace 'com.mercadosjehosua.offlinev3'
    compileSdk 35

    defaultConfig {
        applicationId "com.mercadosjehosua.offlinev3"
        minSdk 23
        targetSdk 35
        versionCode 10
        versionName "3.0.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
